### ISSUE TITLE
Components with modifiers

### ISSUE THREAD

**Issue by cmegown** [HugoGiraudel/jekyll-styleguide#1]
How could we make this work for an individual component that has multiple "options"? For example, you have a button. It's gray and it's awesome and it's everything you want in a button. You know that you also need a red version for deleting things, and maybe a green version for submitting things - the possibilities are endless for your perfect little buttons!

Enter [insert favorite CSS naming convention here].

It makes sense to display the "base" component with a nice description and maybe a few configurable options for whatever framework you happen to be using, but how would we do the same for the various modifiers/options?

**Comment by KittyGiraudel** [comment]
Hey. Thank you for your comment!

I investigated this idea when I first built jekyll-styleguide, and did not find a proper way would did not add a lot of overhead complexity. What I recommend right now is to render several times the same component but with different arguments here: https://github.com/HugoGiraudel/jekyll-styleguide/blob/gh-pages/_styleguide/button.html#L19-L23.

If you’d like to play a bit more with it and come up with a sensible solution, I’d be happy to consider a PR. :)

**Comment by cmegown** [comment]
That's more or less the same conclusion I reached. I'm currently going down the route of just repeating the includes as necessary, which is a bit ugly but _works_. Maybe once things are a bit more built-out I'll see some potential ways to solve this particular issue.
