### ISSUE TITLE
Not so much an issue, more of a discussion

### ISSUE THREAD

**Issue by benoitgrelard** [HugoGiraudel/jekyll-styleguide#2]
Hi @HugoGiraudel,

I have been trying to use Jekyll in a similar fashion as you've done here (reusable components).
I was trying to look if others had done it and had faced some issues I have discovered.
I stumbled upon your project which seems to share a similar approach (for example customisable extra `class` passed to the include by the parent).

I am kind of stuck on this issue here that I have just reported to Jekyll: https://github.com/jekyll/jekyll/issues/5732

I was wondering if you found the same issue (I can't see any example of nested includes here so far, but I'm guessing if you've produced a decently big website with this approach you might have hit it).

Let me know if you did, and if you managed to find a solution.

The obvious fixes I can see for now, although not great, are either:
- always explicitly pass the `class` to all includes
- or if you really don't need one, pass `class=''`

Thanks!

**Comment by KittyGiraudel** [comment]
Interesting discussion, thank you for reporting. I think in my case I always passed a class.
